# SPDX-FileCopyrightText: 2023, Collabora, Ltd.
#
# SPDX-License-Identifier: CC0-1.0
#
# Original author: Rylie Pavlik <rylie.pavlik@collabora.com>

###
# Sample card production config file.
###

# If this file does not exist, it will be generated
# This file contains the pin to actually use the card!
# (as well as the admin key and assigned serial number)
gids_parameters_filename = "samplecard-gids.toml"

# Install and init the GidsApplet, after attempting an uninstall first in case it was already there.
install_and_init_gids = true


# Optionally changing GlobalPlatform ISD keys.
# If you omit this section, we assume the card has default ISD keys and leave it that way when done.
# Not good for production, but good for development/testing.
[gp_config]

# The two gp_parameters_filename fields name TOML files containing ISD lock keys for GlobalPlatform.
# If either one is not specified, the corresponding keys are assumed to be default.
# (404142434445464748494A4B4C4D4E4F)
# If desired_gp_parameters_filename is specified but does not exist, it will first be generated.
#
# Common use cases:
# - If you start with an unused card, specify only desired_gp_parameters_filename,
#   and the card's ISD key will be set to a newly generated key written to that file.
#   You cannot run the production script again on that same card then, because the key is changed!
# - To "unlock" (reset keys to default) a card, specify only current_gp_parameters_filename.
# - To use an already "locked" (non-default keys) card, use the same existing file for
#   current_gp_parameters_filename and desired_gp_parameters_filename

# current_parameters_filename = "sample-gp.toml"
# desired_parameters_filename = "sample-gp.toml"


# Load as many pkcs12 keys as you want (and as will fit)
# Label is your choice, the stuff under .key describes how to parse the p12 file.
[[key_loading]]
label = "signer_s1"
[key_loading.key]
filename = "../keygen-openxr/id_private/signer_s1_testing_private.p12"
passphrase = "asdfs1"

[[key_loading]]
label = "upload_u1"
[key_loading.key]
filename = "../keygen-openxr/id_private/upload_u1_testing_private.p12"
passphrase = "asdfu1"

[[key_loading]]
label = "signer_s3"
[key_loading.key]
filename = "../keygen-openxr/id_private/signer_s3_testing_private.p12"
passphrase = "asdfs3"
